apiVersion: v1
kind: ConfigMap
metadata:
  name: pdx-admin-api-config
  namespace: pdx-admin-interface
data:
  JDK_JAVA_OPTIONS: -Dhttps.proxyHost=hx-wwwcache.ebi.ac.uk -Dhttps.proxyPort=3128 -Dhttp.proxyHost=hx-wwwcache.ebi.ac.uk -Dhttp.proxyPort=3128
  HTTP_PROXY: "http://hx-wwwcache.ebi.ac.uk:3128"
  HTTPS_PROXY: "http://hx-wwwcache.ebi.ac.uk:3128"
  http_proxy: "http://hx-wwwcache.ebi.ac.uk:3128"
  https_proxy: "http://hx-wwwcache.ebi.ac.uk:3128"
  no_proxy: "localhost,.cluster.local"