apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pdx-admin-api-pvc
  namespace: pdx-admin-interface
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: standard-nfs-production
