apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdx-h2-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdx-h2-dev
    spec:
      containers:
        - name: pdx-h2-dev
          image: 'oscarfonts/h2:1.4.197'
          ports:
          - containerPort: 81
          volumeMounts:
            - name: pv-data
              mountPath: /opt/h2-data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: pdx-admin-api-dev-pvc
