apiVersion: v1
kind: Service
metadata:
  name: pdx-h2-dev-service
  labels:
    name: pdx-h2-dev-service
spec:
  ports:
    - name: h2-http
      protocol: TCP
      port: 81
      targetPort: 81
      nodePort: 31933
    - name: h2-tcp
      protocol: TCP
      port: 1521
      targetPort: 1521
      nodePort: 31372
  selector:
    app: pdx-h2-dev
  type: NodePort
