apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdx-admin-api-dev
  namespace: pdx-admin-interface-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdx-admin-api-dev
    spec:
      containers:
        - name: pdx-admin-api-dev
          image: 'pdxfinder/pdx-admin-api:latest'
          imagePullPolicy: Always
          args:
            - --data-base-location=tcp://hh-rke-wp-webadmin-20-worker-1.caas.ebi.ac.uk:31372
            - --data-dir=/opt/pdx-data
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: pdx-admin-api-dev-config
          volumeMounts:
            - name: pv-data
              mountPath: /opt/pdx-data
      volumes:
        - name: pv-data
          persistentVolumeClaim:
            claimName: pdx-admin-api-dev-pvc

