apiVersion: v1
kind: Service
metadata:
  name: pdx-h2-dev-service
  labels:
    name: pdx-h2-dev-service
spec:
  ports:
    - protocol: TCP
      port: 81
      targetPort: 81
  selector:
    app: pdx-h2-dev
  type: NodePort
